//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTran
    {
        public short BookingID { get; set; }
        public string MemberID { get; set; }
        public Nullable<short> FacilityID { get; set; }
        public string FacilityName { get; set; }
        public string Venue { get; set; }
        public Nullable<short> SlotID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string BookStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual Facility Facility { get; set; }
    }
}
