//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string MemberCategory { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> AmountSpent { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Notes { get; set; }
    
        public virtual MemberCategory MemberCategory1 { get; set; }
    }
}
