//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlotName
    {
        public short SlotID { get; set; }
        public string SlotName1 { get; set; }
    }
}
